name: Start build

on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore NuGet packages
      run: nuget restore lab2.sln 

    - name: Build the solution
      run: msbuild lab2.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }}
